name: melanoma_nlp  # Change to your preferred environment name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Ensure compatibility with medspacy and spacy
  - pandas
  - numpy
  - spacy=3.7.5
  - ipython
  - regex
  - jsonschema  # Required for working with JSON validation
  - jupyter
  - scikit-learn 
  - pip
  - pip:
      - medspacy==1.3.1  # Install medspacy from pip 
